# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Joy Marie Navales
title: Mobile Developer
email: jmlnavz12@gmail.com
website: https://github.com/osakalawliet/

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  osakalawliet
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: joymarie.navz
linkedin_username: joy-marie-navales-9ab973198
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi! My name's Joy and I make mobile applications. 

  I am most skilled in <mark>Android</mark> and <mark>iOS</mark> native development.
  
  I am also developing websites using Wordpress and some experience in React, JavaScript, and PHP.
  
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
    - layout: top-middle
        title: Inspectorio Sight
        link: https://apps.apple.com/ph/app/inspectorio-sight/id1533620438
        link_text: App Store
        quote: >
         The largest Saas application I have contributed.
        description: |  # this will include new lines to allow paragraphs
          
          <center><div class="images-container">
          
          <img src="/digital-cv/images/InspectorioSight1.PNG" alt="inspectorio-sight-1"> <img src="/digital-cv/images/InspectorioSight2.PNG" alt="inspectorio-sight-2" class="img-right"> <img src="/digital-cv/images/InspectorioSight3.PNG" alt="inspectorio-sight-3" class="img-right"> <img src="/digital-cv/images/InspectorioSight4.PNG" alt="inspectorio-sight-4" class="img-right">
          </div></center>
          
      - layout: top-middle
        title: ベコ-ベビー写真を可愛くデコ
        link: https://apps.apple.com/jp/app/id1477450497
        link_text: App Store
        quote: >
         This is probably one of the challenging iOS app I have contributed.
        description: |  # this will include new lines to allow paragraphs
          
          <center><div class="images-container">
          
          <img src="/digital-cv/images/beco1.webp" alt="beco1"> <img src="/digital-cv/images/beco2.webp" alt="beco2" class="img-right"> <img src="/digital-cv/images/beco3.webp" alt="beco3" class="img-right"> <img src="/digital-cv/images/beco4.webp" alt="beco4" class="img-right">
          </div></center>
      - layout: top-middle
        title: JRS Mobile
        link: https://www.jrs-express.com/
        link_text: Website
        quote: >
         This is one of the projects where I developed using reactive programming.
        description: |  # this will include new lines to allow paragraphs
          
          <center><div class="images-container">
          
          <img src="/digital-cv/images/JRS1.jpeg" alt="JRS1"> <img src="/digital-cv/images/JRS2.jpeg" alt="JRS2" class="img-right"> <img src="/digital-cv/images/JRS3.jpeg" alt="JRS3" class="img-right"> <img src="/digital-cv/images/JRS4.jpeg" alt="JRS4" class="img-right">
          </div></center>
          
      - layout: top-middle
        title: Maxview Connect
        link: https://apps.apple.com/us/app/maxview-connect/id1357251422
        link_text: App Store
        quote: >
         Probably one of the most challenging projects I made where I integrated the Bluetooth LE API.
        description: |  # this will include new lines to allow paragraphs
          
          <center><div class="images-container">
          <style>
            div.images-container img {
              width: 230px;
              height: 498px;
              object-fit: contain;
              margin-left: 10px;
              margin-right: 10px;
              margin-top: 20px;
            }
            
            .img-bottom {
              margin-top: 20px;
            }
          </style>
          
          <img src="/digital-cv/images/Maxview1.webp" alt="Maxview1"> <img src="/digital-cv/images/Maxview2.webp" alt="Maxview2" class="img-right"> <img src="/digital-cv/images/Maxview3.webp" alt="Maxview3" class="img-right"> <img src="/digital-cv/images/Maxview4.webp" alt="Maxview4" class="img-right">
          </div></center>    
      - layout: top-middle
        title: PhishCloud
        link: https://www.phishcloud.com/
        link_text: Project Website
        quote: > 
         This is where i mostly learned my PHP, JavaScript, CSS, HTML, React, and WordPress skills.     
        description: |  # this will include new lines to allow paragraphs
          
          <center><div>
          
          <img src="/digital-cv/images/phishcloud1.png" alt="phishcloud1">
          <img src="/digital-cv/images/phishcloud2.png" alt="phishcloud2" class="img-bottom">
          </div></center>
          
      - layout: top-middle
        title: 3rd Wave Outsourcing
        link: https://thirdwaveoutsourcing.com/
        link_text: Project Website
        quote: >
         This is one of the sites I have maintained and where I started developing in WordPress.
        description: |  # this will include new lines to allow paragraphs
          
          <center><div>
          
          <img src="/digital-cv/images/thirdwave.png" alt="thirdwave">
          </div></center>
          
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
    - layout: left
        title: Inspectorio, Inc.
        link: https://inspectorio.com
        link_text: inspectorio.com
        sub_title: Mobile Engineer
        caption: January 2022 - Present
        quote: >
          The Inspectorio Platform helps Brands, Retailers, Vendors and Factories to improve their Quality, Compliance and Delivery operations through actionable insights and data-driven collaboration.
        description: | # this will include new lines to allow paragraphs
          - Using Kotlin, Android Jetpack, Swift, and SwiftUI for building native applications in MVVM architecture.
          
          - Developing using WordPress, PHP, HTML, CSS, JavaScript, React andTypeScript
          
          - Creating custom applications for courier services.

          - Practicing leadership skills. 
          
          - Trained fellow developers.
          
          - Used CI/CD Azure DevOps Pipeline.
          
          - Used XCTest for Unit Testing.
          
      - layout: left
        title: ClinkIT Solutions
        link: https://www.clinkitsolutions.com/
        link_text: clinkitsolutions.com
        sub_title: Mobile Developer
        caption: October 2020 - January 2022
        quote: >
          ClinkIT creates proven business solutions by providing software, hardware, and services to more than 100 startups and multinational clients worldwide.
        description: | # this will include new lines to allow paragraphs
          - Using Swift and RxSwift for building native Saas  applications
          
          - Using MVVM, Factory, Abstract Factory, View Model Input-Output Pattern, Facade, Singleton, Command, State, Strategy and Proxy for design pattern
          
          - Using XCTest, Nimble and Cuckoo for unit testing
          
          - Using Fastlane and Bitrise for CI/CD
          
          - Using JIRA for Sprints
          
          - Heavily uses Realm in the in-house applications
          
          - Daily stand-up meeting with the team
          
          - Practices merge request review and approval within the team
          
          - Works closely with the Product Owner and the QA team
          
          - Applied design patterns and coding guidelines for clean, readable, and maintainable codes.



      - layout: left
        title: BBO Co., LTD – Philippine Branch
        link: https://en.bbo.com.ph/
        link_text: bbo.com.ph
        sub_title: Mobile App Developer
        caption: January 2019 - November 2020
        quote: >
          Bbo is a mobile and web design and development agency that is founded on strong business ethics and is driven by dynamic and results-oriented professional web developers from the Philippines and Japan.
        description: | # this will include new lines to allow paragraphs
          - Started developing with Kotlin.

          - Used Android in Java, Kotlin, Swift, and Objective-c for building native applications in MVP architecture.

      - layout: left
        title: Sidekick Digital Limited
        link: https://www.sidekickdigital.co.uk/
        link_text: sidekickdigital.co.uk
        sub_title: Mobile App Developer
        caption: June 2017 - December 2018
        quote: >
          Solve big challenges, build great mobile apps, work better together.
        description: | # this will include new lines to allow paragraphs
          - Started developing with Swift.

          - Used Android in Java and Swift for building native applications.

          - Worked on projects using Bluetooth LE technology.


      - layout: left
        title: Genii Hut Technologies
        link: https://www.geniihut.com/
        link_text: geniihut.com
        sub_title: Mobile Developer
        caption: February 2015 - January 2016
        quote: >
          Genii Hut Technologies Corporation is a company mainly focused on the development of productivity oriented software and applications based on mobile platforms.
        description: | # this will include new lines to allow paragraphs
          - Started developing iOS applications using Objective-c.

          - Used Android in Java and Objective-c for building native applications.
          

      - layout: left
        title: NEXTIX
        link: https://www.nextixsystems.com/
        link_text: nextixsystems.com
        sub_title: Junior Software Developer
        caption: April 2014 - January 2015
        quote: >
          NEXTIX is an award winning technology company  focused on next generation positive impact digital platforms.

        description: | # this will include new lines to allow paragraphs
          - Began my mobile developer career using android.

          - Used Android in Java for building native applications.




  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Cebu Institute Of Technology - University
        caption: 2010 - 2014
        link: https://cit.edu/
        link_text: cit.edu
        sub_title: BS Computer Science
        quote: >
          CIT University is an institution that provides quality education having granted with Autonomous Status in 2016 and recognized as Center of Excellence in Information Technology Education since 2007. 
        description: | # this will include new lines to allow paragraphs
          During my time at CIT University, I learned most of my programming fundamental skills that I have taken throughout my career. I thoroughly enjoyed my time as a university student and learned a lot about technology, teamwork, and communication with other people.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in software engineering, some of my other interests and hobbies are:
      - Travelling
      - Trekking
      - Gaming
      - Coffees and Teas
      - [Experiencing onsen](https://www.youtube.com/watch?v=AUtxQs_fsIA)

      Look at this cool image taken from the internet

      ![Onsen](/digital-cv/images/onsen.jpg "Onsen")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
